Remove more if statements in html from the webiste
JuliaCon/www.juliacon.org pull request #417
Opened 2023-08-07 21:19 UTC by bvdmitri

This PR removes many if statements from HTML files on the website and moves them in one place under `config.md` file. 
It makes it easier to control everything in one place and adds new extra features that were difficult before. For example, now it is easy to use different OpenGraph images per event. This fixes #414. Now each event can customize their OpenGraph metadata, alert messages on the top of the website, header, header colors, and all of it in one place!

![image](https://github.com/JuliaCon/www.juliacon.org/assets/6557701/5b9896fe-9bd1-41d6-a52a-500e1c85b00f)

@cityjumper

2023-08-17 23:19 UTC, pabloferz requested changes

2023-08-17 23:19 UTC, pabloferz commented on config.md
> +        "alert" => """<a href="/2021/prize/">Community Prize</a> | <a href="https://live.juliacon.org">Watch the talks</a> | <a href="https://discourse.julialang.org/t/juliacon-2021-t-shirts-and-stic
```suggestion
        "alert" => """Check out the JuliaCon 2021 <a href="https://www.youtube.com/playlist?list=PLP8iPy9hna6Q343_8sSq4f306VGLW4TLK"videos</a> | <a href="/2021/prize/">Community Prize</a>""",
```

2023-08-17 23:19 UTC, pabloferz commented on config.md
> +        "site_thumbnail" => "../assets/JuliaCon-2023-opengraph.png",
```suggestion
```
I think we can use the default one at this point.

2023-08-18 20:01 UTC, pabloferz approved these changes

2023-08-18 20:03 UTC, merged

2023-08-18 20:03 UTC, pabloferz commented
Thanks for this @bvdmitri!

2023-08-18 21:28 UTC, bvdmitri commented
Glad to help @pabloferz see #420 though, sorry for that! 😬