Template for Keynotes, 2024 edition
JuliaCon/www.juliacon.org pull request #556
Opened 2024-05-17 20:07 UTC by bvdmitri

This PR creates a template for keynotes on the website.

What is missing so far

- [ ] Photo for Andrew
- [ ] Photo for Sam
- [ ] Biography for Michael
- [ ] Biography for Rachel
- [ ] Biography for Andrew
- [ ] Biography for Sam
- [ ] Extra keynotes, which weren't confirmed yet (how many?)
- [ ] Titles? e.g. Dr or Prof.

Overall, the template looks like

![Screenshot 2024-05-17 at 22 06 22](https://github.com/JuliaCon/www.juliacon.org/assets/6557701/042a8ee4-a35e-44a0-92e9-a4d15ff38ef5)

2024-05-18 14:29 UTC, ranjanan requested changes

2024-05-18 14:29 UTC, ranjanan commented on 2024/index.md
> +  \avatar{name="Prof.Dr. Bert de Vries", affil="Eindhoven Technical University", link="https://biaslab.github.io/", img="/assets/2024/img/keynotes/pbert.png"}
Does he go by Prof. Dr. ?

2024-05-18 14:29 UTC, ranjanan commented on 2024/index.md
> +  \avatar{name="Michael F. Herbst", affil="Mathematics and Institute of Materials Science, École polytechnique fédérale de Lausanne, Switzerland", link="https://michael-herbst.com/", img="/assets/202
Prof.

2024-05-18 14:29 UTC, ranjanan commented on 2024/index.md
> +  \avatar{name="Rachel Kurchin", affil="Materials Science and Engineering department at Carnegie Mellon University in Pittsburgh, Pennsylvania, USA", link="https://engineering.cmu.edu/directory/bios/
Prof.

2024-05-18 14:29 UTC, ranjanan commented on 2024/index.md
> +  \avatar{name="Andrew Fitzgibbon", affil="TBF", link="TBF", img="/assets/2024/img/world_768.png"}
Dr.

2024-05-18 14:29 UTC, ranjanan commented on 2024/index.md
> +  \avatar{name="Sam Aaron", affil="TBF", link="TBF", img="/assets/2024/img/world_768.png"}
Dr.

2024-05-18 14:29 UTC, ranjanan commented on 2024/keynotes.md
> +\avatar{name="Michael F. Herbst", affil="Mathematics and Institute of Materials Science, École polytechnique fédérale de Lausanne, Switzerland", link="https://michael-herbst.com/", img="/assets/2024/
Prof.

2024-05-18 14:29 UTC, ranjanan commented on 2024/keynotes.md
> +\avatar{name="Rachel Kurchin", affil="Materials Science and Engineering department at Carnegie Mellon University in Pittsburgh, Pennsylvania, USA", link="https://engineering.cmu.edu/directory/bios/ku
Prof.

2024-05-18 14:29 UTC, ranjanan commented on 2024/keynotes.md
> +\avatar{name="Sam Aaron", affil="TBF", link="TBF", img="/assets/2024/img/world_768.png"}
Dr.

2024-05-18 14:29 UTC, ranjanan commented on 2024/keynotes.md
> +\avatar{name="Andrew Fitzgibbon", affil="TBF", link="TBF", img="/assets/2024/img/world_768.png"}
Dr. 

and affiliation is Graphcore. Ref: https://www.fitzgibbon.ie/

2024-05-18 14:29 UTC, ranjanan commented on 2024/keynotes.md
> +\avatar{name="Sam Aaron", affil="TBF", link="TBF", img="/assets/2024/img/world_768.png"}
Affiliation is Sonic Pi. Website is: https://x.com/i/flow/login?redirect_after_login=%2Fsamaaron.

2024-05-18 14:29 UTC, ranjanan commented on 2024/keynotes.md
> +\avatar{name="Sam Aaron", affil="TBF", link="TBF", img="/assets/2024/img/world_768.png"}
Or: http://sam.aaron.name/

2024-05-19 09:05 UTC, bvdmitri commented on 2024/index.md
> +  \avatar{name="Prof.Dr. Bert de Vries", affil="Eindhoven Technical University", link="https://biaslab.github.io/", img="/assets/2024/img/keynotes/pbert.png"}
Yes, its actually even longer `Prof.Dr.Ir.` but I will double check with him what does he prefer

2024-05-24 14:23 UTC, ranjanan approved these changes

2024-05-24 14:31 UTC, merged