Attempt to rethink the design of the main page for 2024 edition
JuliaCon/www.juliacon.org pull request #579
Opened 2024-06-21 09:41 UTC by bvdmitri

## Briefly Describe your changes

We're keep getting very negative feedback about the layout of the main page of the conference. People are confused with the layout and it looks "childish" with very bright colors. This is really important since nice website boosts ticket sales and grabs attention of more people. This PR is an attempt to rethink the layout of the main page, but of course its not going to be merged without any discussion. I will post a link in the organizers slack channel so people can comment on this changes. 

I was inspired by the [PyData website](https://pydata.org/eindhoven2024), but also tried to keep the original spirit and also kept some of the original elements of the old layout. I also made sure that the new layout displays nicely both on computers and phones. 

I used some old stock photos from JuliaCon Local Eindhoven 2023, but those can be replaced of course.

Use preview to see the changes. In this PR only the main page for 2024 event has been changed. I didn't change previous templates.

## Checklist for merge
- [x] I built the website locally and tested it using `Franklin.serve()`
- [x] All CI checks have passed and you have tested the online version (click on the list of checks and click `Build and Deploy / Preview` to see the preview)
- [ ] Somebody else reviewed my changes (use your best judgement if you need to merge quickly

## After merge
- [ ] Closed relevant issues

2024-06-21 09:46 UTC, NickMcSweeney commented
The page does end up being a bit long, maybe you could put a one line quick link menu-thing at the top.

> keynotes | tickets | venue | sponsors

and clicking on it jumps you down the page.

2024-06-21 12:04 UTC, pabloferz commented
To my eyes, it feels that this leads to too much blank space (which if not there for spacing) which also makes the landing page too long as commented above.

2024-06-21 13:25 UTC, bvdmitri commented
@pabloferz I do think you have a point, this is a different attempt, makes it much more compact
<img width="563" alt="image" src="https://github.com/JuliaCon/www.juliacon.org/assets/6557701/646b82f4-4183-445e-9093-1b61efe910fe">

2024-06-21 14:06 UTC, bvdmitri commented
@NickMcSweeney the page is much shorter now

2024-06-21 14:09 UTC, mkitti commented
I do like the simpler layout. I think it may be possible to use the colors in a limited fashion. Perhaps we could use them for headers somehow. Also check mobile devices please.

2024-06-21 14:12 UTC, bvdmitri commented
Yeah, I've checked the mobile devices right away, they use even simpler "stacked" layout, e.g. this is iPhone
<img width="520" alt="image" src="https://github.com/JuliaCon/www.juliacon.org/assets/6557701/0d8c2a7f-f01a-4034-9ead-f966d6dc089e">
vs iPad (uses normal desktop layout)
<img width="688" alt="image" src="https://github.com/JuliaCon/www.juliacon.org/assets/6557701/497000f8-4844-49bf-a594-0216dbf71777">

2024-06-21 14:19 UTC, bvdmitri commented
@mkitti alternating headers, do you mean something like?
<img width="526" alt="image" src="https://github.com/JuliaCon/www.juliacon.org/assets/6557701/35478ea4-1430-4d40-958f-8c0db8aa24d7">

2024-06-21 14:26 UTC, pabloferz commented
@bvdmitri, the last iteration is much better. I still have other comments:

- I'd say it's better to have something like "JuliaCon at a Glance" than "What to expect".
- The font size within the first all buttons (except for the "Buy your tickets" one) should be bigger
- I'd prefer the buy your tickets smaller but possible in a solid color as opposed to outline colored/white background
- I'd have just "And more!" instead of "And even more!" (it sounds overly redundant IMO)
- Finally I would add some intentional but small extra spacing between sections.

But overall I can get behind the last layout. Well done!

2024-06-21 14:48 UTC, pabloferz requested changes

2024-06-21 14:48 UTC, pabloferz commented on 2024/index.md
> +  @@col-4,col-md-2,align-self-start
```suggestion
  @@col-4,col-md-2,align-self-start,text-center
```

2024-06-21 14:48 UTC, pabloferz commented on 2024/index.md
> +  @@col-4,col-md-2,align-self-start
```suggestion
  @@col-4,col-md-2,align-self-start,text-center
```

2024-06-21 14:48 UTC, pabloferz commented on 2024/index.md
> +  @@col-4,col-md-2,align-self-start
```suggestion
  @@col-4,col-md-2,align-self-start,text-center
```

2024-06-21 14:48 UTC, pabloferz commented on 2024/index.md
> +  @@col-4,col-md-2,align-self-start
```suggestion
  @@col-4,col-md-2,align-self-start,text-center
```

2024-06-21 14:48 UTC, pabloferz commented on 2024/index.md
> +  @@col-4,col-md-2,align-self-start
```suggestion
  @@col-4,col-md-2,align-self-start,text-center
```

2024-06-21 15:29 UTC, mkitti commented
> @mkitti alternating headers, do you mean something like?

I'm not sure I like that. Maybe just have the colors be the background for the headers: "Keynote speakers", "Venue", "Previous",  "Events" with white text.

2024-06-21 15:34 UTC, mkitti commented
Here's what I was thinking for the headers. I'm still deliberating.

![image](https://github.com/JuliaCon/www.juliacon.org/assets/8062771/ecab1548-8740-41ec-9a89-a0d285f87bd8)

2024-06-21 15:36 UTC, mkitti commented
```
element.style {
    background-color: #854c9e;
    color: white;
    border-radius: 1em;
    text-align: center;
}
```

2024-06-21 19:52 UTC, bvdmitri commented
@mkitti this is my attempt, but I'm not sure I like it...

![Screenshot 2024-06-21 at 21 51 49](https://github.com/JuliaCon/www.juliacon.org/assets/6557701/138a7275-5c2f-41c8-8fe8-5b0c09163db4)
 
 vs 
 
 
![Screenshot 2024-06-21 at 21 52 24](https://github.com/JuliaCon/www.juliacon.org/assets/6557701/fd9f67cb-6d2f-41d6-8e18-d2921fde5109)

2024-06-21 20:09 UTC, MaxxxvD commented
Can you add a picture of inside the stadium for under the header “iconic location” instead of the group picture?

2024-06-21 21:56 UTC, mkitti commented
Maybe choose just one color for headers? Perhaps the blue?

And then use another color for the button?

You could also try some shade of gray for either one.

2024-06-22 20:39 UTC, bvdmitri commented
@mkitti I tried a few options, but I’m quite busy this weekend. I also have a list of additional changes to implement over the course of the week. I think we can merge this version for now, and I can work on it further on Monday. WDYT?

2024-06-22 20:42 UTC, bvdmitri commented
@pabloferz I also addressed your request :)

2024-06-22 20:43 UTC, mkitti commented
My main request at the moment is to change the color of the "Buy your ticket here!" button to be distinct from the navigation bar. At the moment it's a slightly different shade of green

2024-06-22 20:58 UTC, bvdmitri commented
I find the purple nice, wdyt @mkitti ? 
<img width="1177" alt="Screenshot 2024-06-22 at 22 56 16" src="https://github.com/JuliaCon/www.juliacon.org/assets/6557701/a154d20f-e1a6-491b-9533-5978a4a1a5bd">
Also red 
<img width="1182" alt="Screenshot 2024-06-22 at 22 56 47" src="https://github.com/JuliaCon/www.juliacon.org/assets/6557701/f9571b84-1ea6-4a76-93af-fcf7ff72e3c8">
also blue
<img width="1213" alt="Screenshot 2024-06-22 at 22 57 10" src="https://github.com/JuliaCon/www.juliacon.org/assets/6557701/17dce0d3-38d1-4704-b6e5-d7f262ae9ae6">

2024-06-22 21:06 UTC, mkitti commented
Purple or blue works for me.

2024-06-22 21:26 UTC, MaxxxvD approved these changes

2024-06-22 23:38 UTC, vchuravy commented
Could we move the Keynote speakers "above the fold". Right underneath the "Buy your ticket here".

Right now you have scroll down quite a bit on a normal 16:9 display.

2024-06-23 13:35 UTC, mkitti commented
@vchuravy Let's rearrange the keynote speakers in a separate PR. I need to add a sponsor.

2024-06-23 13:36 UTC, mkitti approved these changes

2024-06-23 13:36 UTC, merged

2024-06-23 18:05 UTC, bvdmitri commented
@vchuravy imo the position of keynote speakers is fine as it is now, I think its more important to get a simple grasp of the conference first without diving into the details. I also put the link "check out the keynote speakers" under the "insightful keynotes" so its not necessary to scroll all the way down.